name: life_ease
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4
  crop_your_image: ^0.7.5
  share_plus: ^7.2.1
  intl: ^0.19.0
  hive: ^2.2.3
  easy_localization: ^3.0.3
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.2.1
  timezone: ^0.9.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  flutter_plugin_android_lifecycle: ^2.0.15
  # Added for dependency injection
  get_it: ^7.6.7
  # Added for logging
  logging: ^1.2.0
  # Added for state management improvements
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  # Added for API handling
  dio: ^5.4.1
  retrofit: ^4.1.0
  # Added for improved date handling
  jiffy: ^6.2.2
  # Added for data encryption
  encrypt: ^5.0.3
  # Added for form handling
  form_validator: ^2.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.1.2

# Removing dependency overrides which might be causing issues
# dependency_overrides:
#   flutter_plugin_android_lifecycle:
#     path: D:/Pub Cache/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  path: ^1.8.3
  json_serializable: ^6.6.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  bloc_test: ^9.1.6
  mocktail: ^1.0.3
  test: ^1.24.9
  faker: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/translations/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.  uses-material-design: true
